artifacts_root: artifacts

data_ingestion:
  root_dir: arHousingDatatifacts/data_ingestion
  source_URL: https://github.com/naresh198457/MLProjectWithMLFlow/raw/main/HousingData.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

